changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
    - title: Documentation / repo meta
      labels:
        - documentation
        - repo-meta
    - title: Other changes
      labels:
        - "*"
