changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - "type: feature"
        - feature
    - title: Bug fixes
      labels:
        - "type: bug"
    - title: Documentation / repo meta
      labels:
        - "type: docs"
        - "area: repo-meta"
        - repo-meta
    - title: Other changes
      labels:
        - "*"
